<template>
  <div>
    <div class="products__filters">
      <!-- The Filters are dynamically generated by the filterOptions prop -->
      <div v-if="filterOptions.length < 0">
        <h3>Geen filters beschikbaar</h3>
      </div>
      <div v-else>
        <!-- Loop through each filter option -->
        <div v-for="filter in filterOptions" :key="filter.label" class="products__filters">
          <!-- If a filter is a checkbox, render a checkbox with options -->
          <div v-if="filter.filterType === 'checkbox'">
            <CheckBoxFilter :data="filter" @filterCheckBox="filterCheckBox"></CheckBoxFilter>
          </div>

          <!-- If a filter is a radio button, render a radio button -->
          <div v-if="filter.filterType === 'radio'">
            <RadioFilter :data="filter" @filterRadio="filterRadio"></RadioFilter>
          </div>

          <!-- If a filter is a dropdown, render a select with options -->
          <div v-if="filter.filterType === 'dropdown'">
            <DropdownFilter :data="filter" @filterDropdown="filterDropdown"></DropdownFilter>
          </div>

          <!-- If a filter is a range, render input with min max values -->

          <div v-if="filter.filterType === 'range'">
            <RangeFilter :data="filter" @filterRange="filterRange"></RangeFilter>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CheckBoxFilter from "./filters/CheckBoxFilter.vue";
import RadioFilter from "./filters/RadioFilter.vue";
import DropdownFilter from "./filters/DropdownFilter.vue";
import RangeFilter from "./filters/RangeFilter.vue";

export default {
  name: "Filters",
  components: {
    CheckBoxFilter,
    RadioFilter,
    DropdownFilter,
    RangeFilter
  },
  props: {
    filterOptions: Array,
    filterProducts: Function
  },
  data() {
    return {};
  },
  methods: {
    filterCheckBox(filterType, key, value) {
      this.$emit("filterProducts", { filterType, key, value });
    },
    filterRadio(filterType, key, value) {
      this.$emit("filterProducts", { filterType, key, value });
    },
    filterDropdown(filterType, key, value) {
      this.$emit("filterProducts", { filterType, key, value });
    },
    filterRange(filterType, key, value) {
      this.$emit("filterProducts", { filterType, key, value });
    }
  }
};
</script>
